<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="testcases.TestNumberOne" duration-ms="32025" started-at="2022-05-15T01:24:10Z" finished-at="2022-05-15T01:24:43Z">
    <groups>
    </groups>
    <test name="Command line test" duration-ms="32025" started-at="2022-05-15T01:24:10Z" finished-at="2022-05-15T01:24:43Z">
      <class name="testcases.TestNumberOne">
        <test-method status="PASS" signature="browserlauncher()[pri:0, instance:testcases.TestNumberOne@34ce8af7]" name="browserlauncher" is-config="true" duration-ms="24106" started-at="2022-05-14T21:24:10Z" finished-at="2022-05-14T21:24:35Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- browserlauncher -->
        <test-method status="PASS" signature="navigate_to_homepage_click_on_getstarted()[pri:0, instance:testcases.TestNumberOne@34ce8af7]" name="navigate_to_homepage_click_on_getstarted" duration-ms="5147" started-at="2022-05-14T21:24:35Z" finished-at="2022-05-14T21:24:40Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- navigate_to_homepage_click_on_getstarted -->
        <test-method status="FAIL" signature="enter_userDetails()[pri:0, instance:testcases.TestNumberOne@34ce8af7]" name="enter_userDetails" duration-ms="27" started-at="2022-05-14T21:24:40Z" finished-at="2022-05-14T21:24:40Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [App & Browser Testing Made Easy] but found [Create a FREE Account]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [App & Browser Testing Made Easy] but found [Create a FREE Account]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at org.testng.Assert.assertEquals(Assert.java:186)
	at pages.SignUpPage.veryHeader(SignUpPage.java:57)
	at testcases.TestNumberOne.enter_userDetails(TestNumberOne.java:41)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:77)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:110)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:106)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- enter_userDetails -->
        <test-method status="PASS" signature="closeBrowser()[pri:0, instance:testcases.TestNumberOne@34ce8af7]" name="closeBrowser" is-config="true" duration-ms="2600" started-at="2022-05-14T21:24:40Z" finished-at="2022-05-14T21:24:43Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
      </class> <!-- testcases.TestNumberOne -->
    </test> <!-- Command line test -->
  </suite> <!-- testcases.TestNumberOne -->
</testng-results>
